class AlreadyExistsException(Exception):
    pass


class NotExistingException(Exception):
    pass
